### ISSUE TITLE
关于迁移学习的咨询

### ISSUE THREAD

**Issue by yinmingwang** [SkullFang/BERT_NLP_Classification#1]
您好，请问迁移学习的内容在代码中哪儿体现的，我想学习一下在BERT中应用迁移学习。谢谢

**Comment by SkullFang** [comment]
主要在https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py中体现。
具体原理，我最近会在CSDN开一个Chat，会详细讲述BERT原理。包括Transformer，Attention等。
如果你有兴趣可以关注。
https://gitbook.cn/gitchat/activity/5c6a744fff00d04d11dd9d43

**Comment by SkullFang** [comment]
> 您好，请问迁移学习的内容在代码中哪儿体现的，我想学习一下在BERT中应用迁移学习。谢谢
主要在[https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py中体现。](https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py%E4%B8%AD%E4%BD%93%E7%8E%B0%E3%80%82)
具体原理，我最近会在CSDN开一个Chat，会详细讲述BERT原理。包括Transformer，Attention等。
如果你有兴趣可以关注。
https://gitbook.cn/gitchat/activity/5c6a744fff00d04d11dd9d43

**Comment by SkullFang** [comment]
> 您好，请问迁移学习的内容在代码中哪儿体现的，我想学习一下在BERT中应用迁移学习。谢谢

您好

主要在[https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py中体现。](https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py%E4%B8%AD%E4%BD%93%E7%8E%B0%E3%80%82)
具体原理，我最近会在CSDN开一个Chat，会详细讲述BERT原理。包括Transformer，Attention等。
如果你有兴趣可以关注。
https://gitbook.cn/gitchat/activity/5c6a744fff00d04d11dd9d43

**Comment by SkullFang** [comment]
@yinmingwang

**Comment by SkullFang** [comment]
您好

主要在[https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py中体现。](https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py%E4%B8%AD%E4%BD%93%E7%8E%B0%E3%80%82)
具体原理，我最近会在CSDN开一个Chat，会详细讲述BERT原理。包括Transformer，Attention等。
如果你有兴趣可以关注。
https://gitbook.cn/gitchat/activity/5c6a744fff00d04d11dd9d43

**Comment by SkullFang** [comment]
@yinmingwang 
您好

主要在[https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py中体现。](https://github.com/SkullFang/BERT_NLP_Classification/blob/master/run_classifier.py%E4%B8%AD%E4%BD%93%E7%8E%B0%E3%80%82)
具体原理，我最近会在CSDN开一个Chat，会详细讲述BERT原理。包括Transformer，Attention等。
如果你有兴趣可以关注。
https://gitbook.cn/gitchat/activity/5c6a744fff00d04d11dd9d43
